# Use cpp to enable both R & Python
language: r
r: release
pandoc_version: 2.2

sudo: required

os: linux
dist: trusty

branches:
  only:
    - master
    - develop
    - /release\/.*/
    - /hotfix\/.*/
    - /bugfix\/.*/

# Use cache for packages
cache:
  apt: true
  packages: true
  directories:
    - $HOME/miniconda3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - gfortran-7
      - libcurl4-openssl-dev
      - libxml2-dev

matrix:
  include:
  - name: 'Test R codes'
    env: TARGET='R'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
      on:
        branch: hotfix/fix-travis-settings
        condition: $TARGET = R
  - name: 'Test Python codes (Python 3.5)'
    env: TARGET='Python' && PYTHON_VERSION=3.5
  - name: 'Test Python codes (Python 3.6)'
    env: TARGET='Python' && PYTHON_VERSION=3.6
  - name: 'Test Python codes (Python 3.7)'
    env: TARGET='Python' && PYTHON_VERSION=3.7

before_install:
  - export ROOTPATH=`pwd`
  - export MAKEFLAGS='-j 2'
  - export CC=gcc-7
  - export CXX=g++-7
  - if [ "$TARGET" = "R" ]; then cd ./R; fi
  - if [ "$TARGET" = "Python" ]; then cd ./Python; fi

install:
  - source $ROOTPATH/travis/setup.sh

script:
  - source $ROOTPATH/travis/script.sh

after_failure:
  - source $ROOTPATH/travis/after-failure.sh

after_success:
  - source $ROOTPATH/travis/after-success.sh
