language: r

# Be strict when checking our package
warnings_are_errors: false

# Sudo is required
sudo: true

# Use trusty distribution of linux
dist: trusty

# Use both linux and osx operating systems
os:
  - linux
  - osx

# Use cache for packages
cache: packages

# System dependencies for HTTP calling
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libxml2-dev

r:
  - oldrel
  - release
  - devel

script:
  - travis_wait 30 R CMD build .

r_binary_packages:
  - testthat

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
