language: r

# Be strict when checking our package
warnings_are_errors: false

# Sudo is required
sudo: required

# Use trusty distribution of linux
dist: trusty

# Use both linux and osx operating systems
os:
  - linux
  - osx

# System dependencies for HTTP calling
apt_packages:
  - libcurl4-openssl-dev
  - libxml2-dev

install:
  - R -e 'devtools::install_deps(dep = T)'

script:
  - travis_wait 30 R CMD build .
  - travis_wait 30 R CHECK *tar.gz

r_binary_packages:
 - testthat

r_github_packages:
 - jimhester/covr
# - jimhester/lintr

after_success:
 - Rscript -e 'covr::codecov()'
# - Rscript -e 'lintr::lint_package()'
