# Use cpp to enable both R & Python
language: cpp

# NOTE: was `false`
sudo: required

os: linux
dist: trusty

branches:
  only:
    - master
    - develop
    - /release\/.*/
    - /hotfix\/.*/
    - /bugfix\/.*/

# Use cache for packages
cache:
  apt: true
  packages: true
  pip: true
  directories:
    - $HOME/miniconda3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - gcc-7
      - g++-7
      - gfortran-7
      - libcurl4-openssl-dev
      - libxml2-dev

matrix:
  include:
    - name: 'Test sync on models and data'
      env: TARGET='Sync'
    - name: 'Test R codes'
      env: TARGET='R' && MAKEFLAGS='-j 2' && CC=gcc-7 && CXX=g++-7
    - name: 'Test Python codes (Python 3.5)'
      env: TARGET='Python' && PYTHON_VERSION=3.5
#     - name: 'Test Python codes (Python 3.6)'
#       env: TARGET='Python' && PYTHON_VERSION=3.6
#     - name: 'Test Python codes (Python 3.7)'
#       env: TARGET='Python' && PYTHON_VERSION=3.7

before_install:
  - export ROOTPATH=`pwd`
  - [ "$TARGET" = "R" ] && cd ./R
  - [ "$TARGET" = "Python" ] && cd ./Python

install:
  - bash $ROOTPATH/travis/setup.sh

script:
  - bash $ROOTPATH/travis/script.sh

after_failure:
  - bash $ROOTPATH/travis/after-failure.sh

after_success:
  - bash $ROOTPATH/travis/after-success.sh
